version: "3"
services:
  controller:
    image: vc-authn-oidc-controller
    depends_on:
      controller-db:
        condition: service_started
    environment:
      - DB_HOST=${MONGODB_HOST}
      - DB_PORT=${MONGODB_PORT}
      - DB_NAME=${MONGODB_NAME}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_NAME=${REDIS_NAME}
      - OIDC_CONTROLLER_DB_USER=${OIDC_CONTROLLER_DB_USER}
      - OIDC_CONTROLLER_DB_USER_PWD=${OIDC_CONTROLLER_DB_USER_PWD}
      - CONTROLLER_URL=${CONTROLLER_URL}
      - CONTROLLER_URL_LOCAL=${CONTROLLER_URL_LOCAL}
      - ACAPY_TENANCY=${AGENT_TENANT_MODE}
      - ACAPY_AGENT_URL=${AGENT_ENDPOINT}
      - ACAPY_ADMIN_URL=${AGENT_ADMIN_URL}
      - MT_ACAPY_WALLET_ID=${MT_ACAPY_WALLET_ID}
      - MT_ACAPY_WALLET_KEY=${MT_ACAPY_WALLET_KEY}
      - ST_ACAPY_ADMIN_API_KEY=${AGENT_ADMIN_API_KEY}
      - ST_ACAPY_ADMIN_API_KEY_NAME=${ST_ACAPY_ADMIN_API_KEY_NAME}
      - USE_OOB_PRESENT_PROOF=${USE_OOB_PRESENT_PROOF}
    ports:
      - ${CONTROLLER_SERVICE_PORT}:5000
    volumes:
      - ../oidc-controller:/app:rw
    networks:
      - vc_auth

  controller-cache:
    image: 'bitnami/redis:7.0'
    volumes:
      - ./redis-volume:/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
    networks:
      - vc_auth

  controller-db:
    image: mongo:6.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${OIDC_CONTROLLER_DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${OIDC_CONTROLLER_DB_USER_PWD}
      - MONGO_INITDB_DATABASE=${MONGODB_NAME}
    volumes:
      - controller-db-data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - ${MONGODB_PORT}:27017
    restart: unless-stopped
    networks:
      - vc_auth

  keycloak:
    image: jboss/keycloak:16.0.0
    ports:
      - 8880:8080
    volumes:
      - ./keycloak/config:/tmp
    environment:
      DB_VENDOR: ${KEYCLOAK_DB_VENDOR}
      DB_ADDR: ${KEYCLOAK_DB_ADDR}
      DB_DATABASE: ${KEYCLOAK_DB_NAME}
      DB_USER: ${KEYCLOAK_DB_USER}
      DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
      KEYCLOAK_LOGLEVEL: ${KEYCLOAK_LOGLEVEL}
      ROOT_LOGLEVEL: ${KEYCLOAK_ROOT_LOGLEVEL}
      KEYCLOAK_IMPORT: ${KEYCLOAK_IMPORT}
    depends_on:
      - keycloak-db
    networks:
      - vc_auth

  keycloak-db:
    image: postgres:15.1-alpine
    environment:
      - POSTGRES_USER=${KEYCLOAK_DB_USER}
      - POSTGRES_PASSWORD=${KEYCLOAK_DB_PASSWORD}
      - POSTGRES_DB=${KEYCLOAK_DB_NAME}
    volumes:
      - keycloak-db-data:/var/lib/pgsql/data
    networks:
      - vc_auth

  aca-py:
    image: bcgovimages/aries-cloudagent:py36-1.16-1_1.0.0-rc1
    environment:
      - ACAPY_LABEL=${AGENT_NAME}
      - ACAPY_ENDPOINT=${AGENT_ENDPOINT}
      - ACAPY_GENESIS_URL=${GENESIS_URL}
      - ACAPY_WALLET_NAME=oidc_agent_wallet
      - ACAPY_WALLET_TYPE=askar
      - ACAPY_WALLET_KEY=${WALLET_ENCRYPTION_KEY}
      - ACAPY_WALLET_SEED=${AGENT_WALLET_SEED}
      - ACAPY_AUTO_VERIFY_PRESENTATION=true
      - ACAPY_WALLET_STORAGE_TYPE=${WALLET_TYPE}
      - ACAPY_READ_ONLY_LEDGER=true
      - ACAPY_LOG_LEVEL=debug
      - ACAPY_WEBHOOK_URL=${CONTROLLER_WEB_HOOK_URL}
      - ACAPY_AUTO_PROVISION=true
      - POSTGRESQL_WALLET_HOST=${POSTGRESQL_WALLET_HOST}
      - POSTGRESQL_WALLET_PORT=${POSTGRESQL_WALLET_PORT}
      - POSTGRESQL_WALLET_USER=${POSTGRESQL_WALLET_USER}
      - POSTGRESQL_WALLET_PASSWORD=${POSTGRESQL_WALLET_PASSWORD}
    ports:
      - ${AGENT_ADMIN_PORT}:${AGENT_ADMIN_PORT}
      - ${AGENT_HTTP_PORT}:${AGENT_HTTP_PORT}
    networks:
      - vc_auth
    depends_on:
      - wallet-db
    entrypoint: /bin/bash
    command: [
        "-c",
        "sleep 15;
        aca-py start \
        --inbound-transport http '0.0.0.0' ${AGENT_HTTP_PORT} \
        --outbound-transport http \
        --wallet-storage-config '{\"url\":\"${POSTGRESQL_WALLET_HOST}:${POSTGRESQL_WALLET_PORT}\",\"max_connections\":5}' \
        --wallet-storage-creds '{\"account\":\"${POSTGRESQL_WALLET_USER}\",\"password\":\"${POSTGRESQL_WALLET_PASSWORD}\",\"admin_account\":\"${POSTGRESQL_WALLET_USER}\",\"admin_password\":\"${POSTGRESQL_WALLET_PASSWORD}\"}' \ 
        --admin '0.0.0.0' ${AGENT_ADMIN_PORT} \
        --${AGENT_ADMIN_MODE} 
      "
      ]

  wallet-db:
    image: postgres:15.1-alpine
    environment:
      - POSTGRES_USER=${POSTGRESQL_WALLET_USER}
      - POSTGRES_PASSWORD=${POSTGRESQL_WALLET_PASSWORD}
      - POSTGRES_DB=${POSTGRESQL_WALLET_DATABASE}
    networks:
      - vc_auth
    ports:
      - 5433:5432
    volumes:
      - agent-wallet-db:/var/lib/pgsql/data


networks:
  vc_auth:
    driver: bridge


volumes:
  controller-db-data:
  keycloak-db-data:
  agent-wallet-db:
  
