{{- if eq .Values.global.targetPlatform "openshift" -}}
apiVersion: v1
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "vc-authn-oidc.fullname" . }}-ingress
  labels:
    {{- include "vc-authn-oidc.labels" . | nindent 4 }}
spec:
  #  Allow ingress traffic into the controller
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
                network.openshift.io/policy-group: ingress
  podSelector:
    matchLabels:
      {{- include "vc-authn-oidc.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
{{- end }}
