{{- if .Values.networkPolicy.enabled -}}
apiVersion: v1
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "vc-authn-oidc.fullname" . }}-agent-webhook
  labels:
    {{- include "vc-authn-oidc.labels" . | nindent 4 }}
spec:
  # Allow traffic from the agent to the controller
  ingress:
    - from:
        - podSelector:
            matchLabels:
              role: agent
              name: {{ .Values.acaPy.fullnameOverride }}
      ports:
        - protocol: TCP
          port: {{ .Values.service.port }}
  podSelector:
    matchLabels:
      {{- include "vc-authn-oidc.selectorLabels" . | nindent 6 }}
---
apiVersion: v1
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "vc-authn-oidc.fullname" . }}-agent-access
  labels:
    {{- include "vc-authn-oidc.labels" . | nindent 4 }}
spec:
  # Allow traffic from the controller to the agent
  ingress:
    - from:
        - podSelector:
            matchLabels:
              {{- include "vc-authn-oidc.selectorLabels" . | nindent 14 }}
      ports:
        - protocol: TCP
          port: {{ .Values.acaPy.servicePort }}
  podSelector:
    matchLabels:
      # TODO: add proper selector labels for aca-py once sub-chart is ready
      role: agent
      name: {{ .Values.acaPy.fullnameOverride }}
{{- end }}
