{{- if or .Values.networkPolicy.enabled .Values.networkPolicy.ingress.enabled -}}
apiVersion: v1
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "vc-authn-oidc.fullname" . }}-ingress
  labels:
    {{- include "vc-authn-oidc.labels" . | nindent 4 }}
spec:
  #  Allow ingress traffic into the controller
  ingress:
     {{- if and .Values.ingress.enabled .Values.networkPolicy.ingress.enabled (or .Values.networkPolicy.ingress.namespaceSelector .Values.networkPolicy.ingress.podSelector) }}
    - from:
        {{- if .Values.networkPolicy.ingress.namespaceSelector }}
        - namespaceSelector:
            matchLabels:
              {{- include "common.tplvalues.render" (dict "value" .Values.networkPolicy.ingress.namespaceSelector "context" $) | nindent 14 }}
        {{- end }}
        {{- if .Values.networkPolicy.ingress.podSelector }}
        - podSelector:
            matchLabels:
              {{- include "common.tplvalues.render" (dict "value" .Values.networkPolicy.ingress.podSelector "context" $) | nindent 14 }}
        {{- end }}
    {{- end }}
    - from:
        - namespaceSelector:
            matchLabels:
              network.openshift.io/policy-group: ingress
  podSelector:
    matchLabels:
      {{- include "vc-authn-oidc.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
{{- end }}
 